### ISSUE TITLE
Training on 2 GPU's

### ISSUE THREAD

**Issue by israrbacha** [LynnHo/CycleGAN-Tensorflow-2#23]
HI,
thanks for your amazing work, i want to train this model on two rtx 2080ti gpus, do you think that its easy with the existing code or i need to make changes to make it run on 2 gpus?   thanks

**Comment by LynnHo** [comment]
@israrbacha You need to make changes, but I am mot familiar with multiple GPU training of tensorflow 2.0. I will try when I am free.

**Comment by qiuLimoges** [comment]
HI，
I want use your code to train the scanner image which is 16bit grayscale image, I will try to use Pydicom or Tensorflow IO module to read the dcm file. I want to know does you model can train the one channel 16bit Image without modification of the core module?
Thanks

**Comment by LynnHo** [comment]
@qiuLimoges The easiest way I can think of is to convert the 16bit image to RGB image (three identical channels).
